# Generated by Django 3.1.4 on 2020-12-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_top', models.CharField(blank=True, choices=[('Granite', 'Granite'), ('Quartz', 'Quartz'), ('Wood', 'Wood')], default=None, max_length=200, null=True)),
                ('room_shape', models.CharField(blank=True, choices=[('Linear (Two Parallel Lines)', 'Linear (Two Parallel Lines)'), ('L-shaped', 'L-shaped'), ('U-shaped', 'U-shaped')], default=None, max_length=200, null=True)),
                ('refrigerator_style', models.CharField(blank=True, choices=[('Side-By-Side', 'Side-By-Side'), ('Bottom-Freezer', 'Bottom-Freezer'), ('Top-Freezer', 'Top-Freezer')], default=None, max_length=200, null=True)),
            ],
        ),
    ]
