# Generated by Django 3.1.4 on 2020-12-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.CharField(blank=True, choices=[('Twin', 'Twin'), ('Full', 'Full'), ('Queen', 'Queen')], default=None, max_length=200, null=True)),
                ('dressers', models.CharField(blank=True, choices=[('Horizontal', 'Horizontal'), ('Vertical', 'Vertical'), ('Gentlemen Chest', 'Gentlemen Chest')], default=None, max_length=200, null=True)),
                ('desks', models.CharField(blank=True, choices=[('Modern', 'Modern'), ('Small', 'Small'), ('Corner', 'Corner')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_top', models.CharField(blank=True, choices=[('Granite', 'Granite'), ('Quartz', 'Quartz'), ('Wood', 'Wood')], default=None, max_length=200, null=True)),
                ('room_shape', models.CharField(blank=True, choices=[('Linear (Two Parallel Lines)', 'Linear (Two Parallel Lines)'), ('L-shaped', 'L-shaped'), ('U-shaped', 'U-shaped')], default=None, max_length=200, null=True)),
                ('refrigerator_style', models.CharField(blank=True, choices=[('Side-By-Side', 'Side-By-Side'), ('Bottom-Freezer', 'Bottom-Freezer'), ('Top-Freezer', 'Top-Freezer')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofas', models.CharField(blank=True, choices=[('Chesterfield (Classic)', 'Chesterfield (Classic)'), ('Mid-Century (Modern)', 'Mid-Century (Modern)'), ('Lawson (Transitional)', 'Lawson (Transitional)')], default=None, max_length=200, null=True)),
                ('televisions', models.CharField(blank=True, choices=[('OLED', 'OLED'), ('LED', 'LED'), ('Plasma', 'Plasma')], default=None, max_length=200, null=True)),
                ('chairs', models.CharField(blank=True, choices=[('Egg', 'Egg'), ('Wingback', 'Wingback'), ('Chaise Lounge', 'Chaise Lounge')], default=None, max_length=200, null=True)),
            ],
        ),
    ]
